### ISSUE TITLE
Machine manager does not have "hasProperty" function

### ISSUE THREAD

**Issue by nallath** [macdylan/Snapmaker2Plugin#3] opened 2022-05-24 13:46 UTC
stack3 is set to be the MachineManager
https://github.com/macdylan/Snapmaker2Plugin/blob/427028662f72829d3dfeda04fcad55db9297204f/SM2GCodeWriter.py#L125

This is already a bit odd variable naming, as the MachineManager isn't a stack, but it's also treated a bit later as if it's an actual stack:
https://github.com/macdylan/Snapmaker2Plugin/blob/427028662f72829d3dfeda04fcad55db9297204f/SM2GCodeWriter.py#L132-L133

But the MachineManager doesn't even have a function called "hasProperty". I expect that this code isn't ever hit, as the "real" stacks generally do have the property that you ask for.

**Comment by macdylan** [comment] 2022-05-24 15:00
Duplicate of #4

**Closed** 2022-05-24 15:00 UTC
