### ISSUE TITLE
Option to simplify code

### ISSUE THREAD

**Issue by nallath** [macdylan/Snapmaker2Plugin#4] opened 2022-05-24 13:54 UTC
The following code does a lot of things that aren't really needed
https://github.com/macdylan/Snapmaker2Plugin/blob/427028662f72829d3dfeda04fcad55db9297204f/SM2GCodeWriter.py#L121-L137

If you ask the extruder stack for "hasProperty", it will _always_ return true if the global stack that it's connected to also has it. As such, the stack will always be stack1.

The code can then be simplified to:
```python3
stack = ExtruderManager.getInstance().getActiveExtruderStack() 
if not stack: 
         return ""
# Rest of the code
```

**Comment by macdylan** [comment] 2022-05-24 14:59
Duplicate of #3 

fixed: 20dd7a6d62dd241b8452f780426cda24a79d7fe8

Thanks for your help.

**Closed as completed by macdylan** 2022-05-24 14:59 UTC
